//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _91App_Test
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class tOrderList
    {
        public int forderListId { get; set; }
        [DisplayName("Order Id")]
        public string fId { get; set; }
        [DisplayName("Order Item")]
        public string fItem { get; set; }
        [DisplayName("Price")]
        public Nullable<int> fPrice { get; set; }
        [DisplayName("Cost")]
        public Nullable<int> fCost { get; set; }
        [DisplayName("Status")]
        public Nullable<int> fOrderStatus { get; set; }
    }
}
