//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _91App_Test
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class tProduct
    {
        public short fProductId { get; set; }
        public string fProductName { get; set; }
        public Nullable<int> fProductPrice { get; set; }
        public string fProductBrand { get; set; }
        public Nullable<byte> fPayByCard { get; set; }
        public Nullable<byte> fPayByArrive { get; set; }
        public Nullable<byte> fPayByLinePay { get; set; }
        public Nullable<byte> fPayByJKO { get; set; }
        public Nullable<byte> fInstallment { get; set; }
        public Nullable<byte> fInstallmentRate { get; set; }
        public Nullable<byte> fDelivery { get; set; }
        public Nullable<short> fStock { get; set; }
        public string fProductImage { get; set; }
        public HttpPostedFileBase fImage { get; set; }
        public int[] fPayBy { get; set; }
        public int[] fDeliveryTo { get; set; }
    }
}
